{{- if .Values.prometheusOperator.networkPolicy.enabled }}
apiVersion: {{ template "kube-prometheus-stack.prometheus.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  {{- if .Values.heritageNameOverride }}
  name: {{ include "prometheus-operator.heritageName" . }}
  {{- else }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-operator
  {{- end }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    {{- if .Values.heritageNameOverride }}
    app: {{ include "prometheus-operator.heritageName" . }}
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" . }}-operator
    {{- end }}
spec:
  egress: 
    - {}
  ingress:
    - ports:
      {{- if .Values.prometheusOperator.tls.enabled }}
      - port: {{ .Values.prometheusOperator.tls.internalPort }}
      {{- else }}
      - port: 8080
      {{- end }}
  policyTypes:
    - Egress
    - Ingress
  podSelector:
    matchLabels:
      {{- if .Values.heritageNameOverride }}
      app: {{ include "prometheus-operator.heritageName" . }}
      {{- else }}
      app: {{ template "kube-prometheus-stack.name" . }}-operator
      {{- end }}
      release: {{ $.Release.Name | quote }}
{{- end }}
