{{- if and .Values.prometheusOperator.enabled .Values.prometheusOperator.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  {{- if .Values.heritageNameOverride }}
  name: {{ include "prometheus-operator.heritageName" . }}
  {{- else }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-operator
  {{- end }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    {{- if .Values.heritageNameOverride }}
    app: {{ include "prometheus-operator.heritageName" . }}
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" . }}-operator
    {{- end }}
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
{{- include "kubesphere-monitor.labels" . | indent 4 }}
spec:
  endpoints:
  {{- if .Values.prometheusOperator.tls.enabled }}
  - port: https
    scheme: https
    tlsConfig:
      {{- if .Values.heritageNameOverride }}
      serverName: {{ include "prometheus-operator.heritageName" . }}
      {{- else }}
      serverName: {{ template "kube-prometheus-stack.operator.fullname" . }}
      {{- end }}
      ca:
        secret:
          {{- if .Values.heritageNameOverride }}
          name: {{ include "prometheus-operator.heritageName" . }}-admission
          {{- else }}
          name: {{ template "kube-prometheus-stack.fullname" . }}-admission
          {{- end }}
          key: {{ if .Values.prometheusOperator.admissionWebhooks.certManager.enabled }}ca.crt{{ else }}ca{{ end }}
          optional: false
  {{- else }}
  - port: http
  {{- end }}
    honorLabels: true
    {{- if .Values.prometheusOperator.serviceMonitor.interval }}
    interval: {{ .Values.prometheusOperator.serviceMonitor.interval }}
    {{- end }}
{{- if .Values.prometheusOperator.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.prometheusOperator.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.prometheusOperator.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.prometheusOperator.serviceMonitor.relabelings | indent 6 }}
{{- end }}
  selector:
    matchLabels:
      {{- if .Values.heritageNameOverride }}
      app: {{ include "prometheus-operator.heritageName" . }}
      {{- else }}
      app: {{ template "kube-prometheus-stack.name" . }}-operator
      {{- end }}
      release: {{ $.Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - {{ printf "%s" (include "kube-prometheus-stack.namespace" .) | quote }}
{{- end }}
