{{- if .Values.thanosRuler.extraSecret.data -}}
{{- $secretName := printf "thanos-ruler-%s-extra" (include "kube-prometheus-stack.fullname" . ) -}}
{{- if .Values.heritageNameOverride }}
{{- $secretName = printf "thanos-ruler-%s-extra" (include "thanos-ruler.heritageName" . ) -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default $secretName .Values.thanosRuler.extraSecret.name }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
{{- if .Values.thanosRuler.extraSecret.annotations }}
  annotations:
{{ toYaml .Values.thanosRuler.extraSecret.annotations | indent 4 }}
{{- end }}
  labels:
    {{- if .Values.heritageNameOverride }}
    app: thanos-ruler-{{ include "thanos-ruler.heritageName" . }}
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" . }}-thanos-ruler
    {{- end }}
    app.kubernetes.io/component: thanos-ruler
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
data:
{{- range $key, $val := .Values.thanosRuler.extraSecret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
