{{- if and .Values.prometheusOperator.enabled .Values.prometheusOperator.admissionWebhooks.enabled .Values.prometheusOperator.admissionWebhooks.patch.enabled (not .Values.prometheusOperator.admissionWebhooks.certManager.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  {{- if .Values.heritageNameOverride }}
  name: {{ include "prometheus-operator.heritageName" . }}-admission-create
  {{- else }}
  name:  {{ template "kube-prometheus-stack.fullname" . }}-admission-create
  {{- end }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- with .Values.prometheusOperator.admissionWebhooks.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}   
  labels:
    {{- if .Values.heritageNameOverride }}
    app: {{ include "prometheus-operator.heritageName" $ }}-admission-create
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" $ }}-admission-create
    {{- end }}
{{- include "kube-prometheus-stack.labels" $ | indent 4 }}
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
      {{- if .Values.heritageNameOverride }}
      name: {{ include "prometheus-operator.heritageName" . }}-admission-create
      {{- else }}
      name:  {{ template "kube-prometheus-stack.fullname" . }}-admission-create
      {{- end }}
{{- with .Values.prometheusOperator.admissionWebhooks.patch.podAnnotations }}
      annotations:
{{ toYaml .  | indent 8 }}
{{- end }}
      labels:
        {{- if .Values.heritageNameOverride }}
        app: {{ include "prometheus-operator.heritageName" $ }}-admission-create
        {{- else }}
        app: {{ template "kube-prometheus-stack.name" $ }}-admission-create
        {{- end }}
{{- include "kube-prometheus-stack.labels" $ | indent 8 }}
    spec:
      {{- if .Values.prometheusOperator.admissionWebhooks.patch.priorityClassName }}
      priorityClassName: {{ .Values.prometheusOperator.admissionWebhooks.patch.priorityClassName }}
      {{- end }}
      containers:
        - name: create
          {{- $registry := .Values.global.imageRegistry | default .Values.prometheusOperator.admissionWebhooks.patch.image.registry -}}
          {{- if .Values.prometheusOperator.admissionWebhooks.patch.image.sha }}
          image: {{ $registry }}/{{ .Values.prometheusOperator.admissionWebhooks.patch.image.repository }}:{{ .Values.prometheusOperator.admissionWebhooks.patch.image.tag }}@sha256:{{ .Values.prometheusOperator.admissionWebhooks.patch.image.sha }}
          {{- else }}
          image: {{ $registry }}/{{ .Values.prometheusOperator.admissionWebhooks.patch.image.repository }}:{{ .Values.prometheusOperator.admissionWebhooks.patch.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.prometheusOperator.admissionWebhooks.patch.image.pullPolicy }}
          args:
            - create
            {{- if .Values.heritageNameOverride }}
            - --host={{ include "prometheus-operator.heritageName" . }},{{ include "prometheus-operator.heritageName" . }}.{{ template "kube-prometheus-stack.namespace" . }}.svc
            {{- else }}
            - --host={{ template "kube-prometheus-stack.operator.fullname" . }},{{ template "kube-prometheus-stack.operator.fullname" . }}.{{ template "kube-prometheus-stack.namespace" . }}.svc
            {{- end }}
            - --namespace={{ template "kube-prometheus-stack.namespace" . }}
            {{- if .Values.heritageNameOverride }}
            - --secret-name={{ include "prometheus-operator.heritageName" . }}-admission
            {{- else }}
            - --secret-name={{ template "kube-prometheus-stack.fullname" . }}-admission
            {{- end }}
          {{- with .Values.prometheusOperator.admissionWebhooks.createSecretJob }}
          securityContext:
          {{ toYaml .securityContext | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.prometheusOperator.admissionWebhooks.patch.resources | indent 12 }}
      restartPolicy: OnFailure
      {{- if .Values.heritageNameOverride }}
      serviceAccountName: {{ include "prometheus-operator.heritageName" . }}-admission
      {{- else }}
      serviceAccountName: {{ template "kube-prometheus-stack.fullname" . }}-admission
      {{- end }}
      {{- with .Values.prometheusOperator.admissionWebhooks.patch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.prometheusOperator.admissionWebhooks.patch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.prometheusOperator.admissionWebhooks.patch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- if .Values.prometheusOperator.admissionWebhooks.patch.securityContext }}
      securityContext:
{{ toYaml .Values.prometheusOperator.admissionWebhooks.patch.securityContext | indent 8 }}
{{- end }}
{{- end }}
