{{- if .Values.prometheusOperator.networkPolicy.enabled }}
{{- if and .Values.prometheusOperator.enabled .Values.prometheusOperator.admissionWebhooks.enabled .Values.prometheusOperator.admissionWebhooks.patch.enabled (not .Values.prometheusOperator.admissionWebhooks.certManager.enabled) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{- if .Values.heritageNameOverride }}
  name: {{ include "prometheus-operator.heritageName" . }}-admission-create
  {{- else }}
  name:  {{ template "kube-prometheus-stack.fullname" . }}-admission-create
  {{- end }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    ## Ensure this is run before the job
    "helm.sh/hook-weight": "-5"
{{- with .Values.prometheusOperator.admissionWebhooks.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}   
  labels:
    {{- if .Values.heritageNameOverride }}
    app: {{ include "prometheus-operator.heritageName" $ }}-admission-create
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" $ }}-admission-create
    {{- end }}
{{- include "kube-prometheus-stack.labels" $ | indent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- if .Values.heritageNameOverride }}
      app: {{ include "prometheus-operator.heritageName" $ }}-admission-create
      {{- else }}
      app: {{ template "kube-prometheus-stack.name" $ }}-admission-create
      {{- end }}
{{- include "kube-prometheus-stack.labels" $ | indent 6 }}
  egress:
  - {}
  policyTypes:
  - Egress
{{- end }}
{{- end }}
