{{- if .Values.kubeRBACProxy.enabled }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "prometheus-blackbox-exporter.labels" . | nindent 4 }}
  name: {{ template "prometheus-blackbox-exporter.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "prometheus-blackbox-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-blackbox-exporter.serviceAccountName" . }}
    namespace: {{ template "prometheus-blackbox-exporter.namespace" . }}
{{- end }}
