{{- if .Values.kubeRBACProxy.enabled }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
    {{- include "prometheus-blackbox-exporter.labels" . | nindent 4 }}
  name: {{ template "prometheus-blackbox-exporter.fullname" . }}
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - subjectaccessreviews
    verbs: ["create"]
{{- end }}
