{{- if and .Values.kubeEtcd.enabled .Values.kubeEtcd.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.heritageNameOverride }}
  name: etcd
  {{- else }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-kube-etcd
  {{- end }}
  labels:
    {{- if .Values.heritageNameOverride }}
    app: etcd
    jobLabel: etcd
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" . }}-kube-etcd
    jobLabel: kube-etcd
    {{- end }}
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeEtcd.service.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeEtcd.service.targetPort }}
{{- if .Values.kubeEtcd.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeEtcd.service.selector }}
{{ toYaml .Values.kubeEtcd.service.selector | indent 4 }}
    {{- else}}
    component: etcd
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end -}}
