{{- if and .Values.alertmanager.enabled .Values.alertmanager.heritageName}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.alertmanager.heritageName }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-alertmanager
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
{{- if .Values.alertmanager.service.labels }}
{{ toYaml .Values.alertmanager.service.labels | indent 4 }}
{{- end }}
{{- if .Values.alertmanager.service.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.service.annotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: {{ .Values.alertmanager.alertmanagerSpec.portName }}
    port: {{ .Values.alertmanager.service.port }}
    targetPort: {{ .Values.alertmanager.service.targetPort }}
    protocol: TCP
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector:
    app.kubernetes.io/name: alertmanager
    alertmanager: {{ template "kube-prometheus-stack.alertmanager.crname" . }}
{{- if .Values.alertmanager.service.sessionAffinity }}
  sessionAffinity: {{ .Values.alertmanager.service.sessionAffinity }}
{{- end }}
  type: ClusterIP
{{- end }}
