{{- if and .Values.alertmanager.enabled .Values.alertmanager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.heritageNameOverride }}
  name: alertmanager-{{ include "alertmanager.heritageName" . }}
  {{- else }}
  name: {{ template "kube-prometheus-stack.alertmanager.serviceAccountName" . }}
  {{- end }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    {{- if .Values.heritageNameOverride }}
    app: alertmanager-{{ include "alertmanager.heritageName" . }}
    app.kubernetes.io/name: alertmanager-{{ include "alertmanager.heritageName" . }}
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" . }}-alertmanager
    app.kubernetes.io/name: {{ template "kube-prometheus-stack.name" . }}-alertmanager
    {{- end }}
    app.kubernetes.io/component: alertmanager
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
{{- if .Values.alertmanager.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{ include "kube-prometheus-stack.imagePullSecrets" . | trim | indent 2}}
{{- end }}
{{- end }}
