{{- if and .Values.alertmanager.enabled .Values.alertmanager.serviceMonitor.selfMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  {{- if .Values.heritageNameOverride }}
  name: alertmanager-{{ include "alertmanager.heritageName" . }}
  {{- else }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-alertmanager
  {{- end }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    {{- if .Values.heritageNameOverride }}
    app: alertmanager-{{ include "alertmanager.heritageName" . }}
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" . }}-alertmanager
    {{- end }}
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- if .Values.heritageNameOverride }}
      app: alertmanager-{{ include "alertmanager.heritageName" . }}
      {{- else }}
      app: {{ template "kube-prometheus-stack.name" . }}-alertmanager
      {{- end }}
      release: {{ $.Release.Name | quote }}
      self-monitor: "true"
  namespaceSelector:
    matchNames:
      - {{ printf "%s" (include "kube-prometheus-stack.namespace" .) | quote }}
  endpoints:
  - port: {{ .Values.alertmanager.alertmanagerSpec.portName }}
    enableHttp2: {{ .Values.alertmanager.serviceMonitor.enableHttp2 }}
    {{- if .Values.alertmanager.serviceMonitor.interval }}
    interval: {{ .Values.alertmanager.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.alertmanager.serviceMonitor.proxyUrl }}
    proxyUrl: {{ .Values.alertmanager.serviceMonitor.proxyUrl}}
    {{- end }}
    {{- if .Values.alertmanager.serviceMonitor.scheme }}
    scheme: {{ .Values.alertmanager.serviceMonitor.scheme }}
    {{- end }}
    {{- if .Values.alertmanager.serviceMonitor.bearerTokenFile }}
    bearerTokenFile: {{ .Values.alertmanager.serviceMonitor.bearerTokenFile }}
    {{- end }}
    {{- if .Values.alertmanager.serviceMonitor.tlsConfig }}
    tlsConfig: {{ toYaml .Values.alertmanager.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    path: "{{ trimSuffix "/" .Values.alertmanager.alertmanagerSpec.routePrefix }}/metrics"
{{- if .Values.alertmanager.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.alertmanager.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.alertmanager.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.alertmanager.serviceMonitor.relabelings | indent 6 }}
{{- end }}
{{- end }}
