# Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

global:
  imageRegistry: ""
  imagePullSecrets: []

image:
  registry: docker.io
  repository: kubesphere/dcgm-exporter
  pullPolicy: IfNotPresent
  # Image tag defaults to AppVersion, but you can use the tag key
  # for the image tag, e.g:
  tag: 3.3.5-3.4.0-ubuntu22.04

# Change the following reference to "/etc/dcgm-exporter/default-counters.csv"
# to stop profiling metrics from DCGM
arguments:
  - "-f"
  - "/etc/dcgm-exporter/custom-dcgm-metrics.csv"
# default arguments:
# ["-f", "/etc/dcgm-exporter/dcp-metrics-included.csv"]
# NOTE: in general, add any command line arguments to arguments above
# and they will be passed through.
# Use "-r", "<HOST>:<PORT>" to connect to an already running hostengine
# Example arguments: ["-r", "host123:5555"]
# Use "-n" to remove the hostname tag from the output.
# Example arguments: ["-n"]
# Use "-d" to specify the devices to monitor. -d must be followed by a string
# in the following format: [f] or [g[:numeric_range][+]][i[:numeric_range]]
# Where a numeric range is something like 0-4 or 0,2,4, etc.
# Example arguments: ["-d", "g+i"] to monitor all GPUs and GPU instances or
# ["-d", "g:0-3"] to monitor GPUs 0-3.
# Use "-m" to specify the namespace and name of a configmap containing
# the watched exporter fields.
# Example arguments: ["-m", "default:exporter-metrics-config-map"]

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

runtimeClassName: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

rollingUpdate:
  # Specifies maximum number of DaemonSet pods that can be unavailable during the update
  maxUnavailable: 1
  # Specifies maximum number of nodes with an existing available DaemonSet pod that can have an updated DaemonSet pod during during an update
  maxSurge: 0

podLabels: {}

podAnnotations: {}
# Using this annotation which is required for prometheus scraping
 # prometheus.io/scrape: "true"
 # prometheus.io/port: "9400"

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: false
  runAsUser: 0
  capabilities:
    add: ["SYS_ADMIN"]
  # readOnlyRootFilesystem: true

service:
  enable: true
  type: ClusterIP
  port: 9400
  address: ":9400"
  # Annotations to add to the service
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceMonitor:
  enabled: true
  interval: 15s
  honorLabels: true
  additionalLabels: {}
    # monitoring: prometheus
  relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace

nodeSelector: {}
  # node: gpu

tolerations: []
  # - operator: Exists

affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: nvidia-gpu
  #         operator: Exists

extraHostVolumes: []
  # - name: host-binaries
  #   hostPath: /opt/bin

extraConfigMapVolumes:
  - name: custom-dcgm-metrics
    configMap:
      name: custom-dcgm-metrics-configmap

extraVolumeMounts:
  - name: custom-dcgm-metrics
    mountPath: /etc/dcgm-exporter/custom-dcgm-metrics.csv
    subPath: custom-dcgm-metrics.csv
    readOnly: true

extraEnv: []
  #  - name: EXTRA_VAR
  #    value: "TheStringValue"

kubeletPath: "/var/lib/kubelet/pod-resources"


extraManifests:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: custom-dcgm-metrics-configmap
      namespace: '{{ include "dcgm-exporter.namespace" . }}'
    data:
      custom-dcgm-metrics.csv: |
          # Format
          # If line starts with a '#' it is considered a comment
          # DCGM FIELD, Prometheus metric type, help message

          # Clocks
          DCGM_FI_DEV_SM_CLOCK,  gauge, SM clock frequency (in MHz).
          DCGM_FI_DEV_MEM_CLOCK, gauge, Memory clock frequency (in MHz).

          # Temperature
          DCGM_FI_DEV_MEMORY_TEMP, gauge, Memory temperature (in C).
          DCGM_FI_DEV_GPU_TEMP,    gauge, GPU temperature (in C).

          # Power
          DCGM_FI_DEV_POWER_USAGE,              gauge, Power draw (in W).
          DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION, counter, Total energy consumption since boot (in mJ).

          # PCIE
          # DCGM_FI_DEV_PCIE_TX_THROUGHPUT,  counter, Total number of bytes transmitted through PCIe TX (in KB) via NVML.
          # DCGM_FI_DEV_PCIE_RX_THROUGHPUT,  counter, Total number of bytes received through PCIe RX (in KB) via NVML.
          DCGM_FI_DEV_PCIE_REPLAY_COUNTER, counter, Total number of PCIe retries.

          # Utilization (the sample period varies depending on the product)
          DCGM_FI_DEV_GPU_UTIL,      gauge, GPU utilization (in %).
          DCGM_FI_DEV_MEM_COPY_UTIL, gauge, Memory utilization (in %).
          DCGM_FI_DEV_ENC_UTIL,      gauge, Encoder utilization (in %).
          DCGM_FI_DEV_DEC_UTIL ,     gauge, Decoder utilization (in %).

          # Errors and violations
          DCGM_FI_DEV_XID_ERRORS,            gauge,   Value of the last XID error encountered.
          DCGM_FI_DEV_POWER_VIOLATION,       counter, Throttling duration due to power constraints (in us).
          DCGM_FI_DEV_THERMAL_VIOLATION,     counter, Throttling duration due to thermal constraints (in us).
          DCGM_FI_DEV_SYNC_BOOST_VIOLATION,  counter, Throttling duration due to sync-boost constraints (in us).
          DCGM_FI_DEV_BOARD_LIMIT_VIOLATION, counter, Throttling duration due to board limit constraints (in us).
          DCGM_FI_DEV_LOW_UTIL_VIOLATION,    counter, Throttling duration due to low utilization (in us).
          DCGM_FI_DEV_RELIABILITY_VIOLATION, counter, Throttling duration due to reliability constraints (in us).

          # Memory usage
          DCGM_FI_DEV_FB_FREE, gauge, Framebuffer memory free (in MiB).
          DCGM_FI_DEV_FB_USED, gauge, Framebuffer memory used (in MiB).

          # ECC
          # DCGM_FI_DEV_ECC_SBE_VOL_TOTAL, counter, Total number of single-bit volatile ECC errors.
          # DCGM_FI_DEV_ECC_DBE_VOL_TOTAL, counter, Total number of double-bit volatile ECC errors.
          # DCGM_FI_DEV_ECC_SBE_AGG_TOTAL, counter, Total number of single-bit persistent ECC errors.
          # DCGM_FI_DEV_ECC_DBE_AGG_TOTAL, counter, Total number of double-bit persistent ECC errors.

          # Retired pages
          DCGM_FI_DEV_RETIRED_SBE,     counter, Total number of retired pages due to single-bit errors.
          DCGM_FI_DEV_RETIRED_DBE,     counter, Total number of retired pages due to double-bit errors.
          DCGM_FI_DEV_RETIRED_PENDING, counter, Total number of pages pending retirement.

          # NVLink
          DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL, counter, Total number of NVLink flow-control CRC errors.
          DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL, counter, Total number of NVLink data CRC errors.
          DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_TOTAL,   counter, Total number of NVLink retries.
          DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL, counter, Total number of NVLink recovery errors.
          DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL,            counter, Total number of NVLink bandwidth counters for all lanes.
          # DCGM_FI_DEV_NVLINK_BANDWIDTH_L0,               counter, The number of bytes of active NVLink rx or tx data including both header and payload.

          # VGPU License status
          DCGM_FI_DEV_VGPU_LICENSE_STATUS, gauge, vGPU License status

          # Remapped rows
          DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS, counter, Number of remapped rows for uncorrectable errors
          DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS,   counter, Number of remapped rows for correctable errors
          DCGM_FI_DEV_ROW_REMAP_FAILURE,           gauge,   Whether remapping of rows has failed

          # Static configuration information. These appear as labels on the other metrics
          DCGM_FI_DRIVER_VERSION,        label, Driver Version
          DCGM_FI_NVML_VERSION,          label, NVML Version
          DCGM_FI_DEV_BRAND,             label, Device Brand
          DCGM_FI_DEV_SERIAL,            label, Device Serial Number
          DCGM_FI_DEV_OEM_INFOROM_VER,   label, OEM inforom version
          DCGM_FI_DEV_ECC_INFOROM_VER,   label, ECC inforom version
          DCGM_FI_DEV_POWER_INFOROM_VER, label, Power management object inforom version
          DCGM_FI_DEV_INFOROM_IMAGE_VER, label, Inforom image version
          DCGM_FI_DEV_VBIOS_VERSION,     label, VBIOS version of the device

          # DCP metrics
          DCGM_FI_PROF_GR_ENGINE_ACTIVE,   gauge, Ratio of time the graphics engine is active (in %).
          DCGM_FI_PROF_SM_ACTIVE,          gauge, The ratio of cycles an SM has at least 1 warp assigned (in %).
          DCGM_FI_PROF_SM_OCCUPANCY,       gauge, The ratio of number of warps resident on an SM (in %).
          DCGM_FI_PROF_PIPE_TENSOR_ACTIVE, gauge, Ratio of cycles the tensor (HMMA) pipe is active (in %).
          DCGM_FI_PROF_DRAM_ACTIVE,        gauge, Ratio of cycles the device memory interface is active sending or receiving data (in %).
          DCGM_FI_PROF_PIPE_FP64_ACTIVE,   gauge, Ratio of cycles the fp64 pipes are active (in %).
          DCGM_FI_PROF_PIPE_FP32_ACTIVE,   gauge, Ratio of cycles the fp32 pipes are active (in %).
          DCGM_FI_PROF_PIPE_FP16_ACTIVE,   gauge, Ratio of cycles the fp16 pipes are active (in %).
          DCGM_FI_PROF_PCIE_TX_BYTES,      gauge, The rate of data transmitted over the PCIe bus - including both protocol headers and data payloads - in bytes per second.
          DCGM_FI_PROF_PCIE_RX_BYTES,      gauge, The rate of data received over the PCIe bus - including both protocol headers and data payloads - in bytes per second.


          # Additional recommended fields
          DCGM_FI_DEV_COUNT                                                 ,counter                ,Number of Devices on the node.
          DCGM_FI_DEV_POWER_MGMT_LIMIT                                      ,gauge                  ,Current power limit for the device.
          DCGM_FI_DEV_PSTATE                                                ,gauge                  ,Performance state (P-State) 0-15. 0=highest
          DCGM_FI_DEV_FB_TOTAL                                              ,gauge                  ,
          DCGM_FI_DEV_FB_RESERVED                                           ,gauge                  ,
          DCGM_FI_DEV_FB_USED_PERCENT                                       ,gauge                  ,
          DCGM_FI_DEV_CLOCK_THROTTLE_REASONS                                ,gauge                  ,Current clock throttle reasons

          DCGM_FI_PROCESS_NAME                                              ,label                  ,The Process Name.
          DCGM_FI_CUDA_DRIVER_VERSION                                       ,label                  ,CUDA driver version
          DCGM_FI_DEV_NAME                                                  ,label                  ,The Device Name
