global:
  ## Global image registry to use if it needs to be overriden for some specific use cases (e.g local registries, custom images, ...)
  ##
  imageRegistry: ""

  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"
  # or
  # - "image-pull-secret"


prometheus:
  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: ""
    replicas: 1
    resources:
      limits:
        cpu: "4"
        memory: 16Gi
      requests:
        cpu: 200m
        memory: 400Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi

prometheusOperator:
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-operator
    tag: ""
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

  prometheusConfigReloader:
    image:
      registry: quay.io
      repository: prometheus-operator/prometheus-config-reloader
      tag: ""
      sha: ""
    resources:
      requests:
        cpu: 200m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 50Mi

kube-state-metrics:
  image:
    registry: docker.io
    repository: kubesphere/kube-state-metrics
    tag: v2.8.2
  resources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: 10m
      memory: 190Mi
  kubeRBACProxy:
    image:
      registry: quay.io
      repository: brancz/kube-rbac-proxy
      tag: v0.14.0
    resources:
      limits:
        cpu: 40m
        memory: 40Mi
      requests:
        cpu: 20m
        memory: 20Mi


prometheus-node-exporter:
  image:
    registry: quay.io
    repository: prometheus/node-exporter
    tag: ""
  resources:
    limits:
      cpu: 250m
      memory: 180Mi
    requests:
      cpu: 102m
      memory: 180Mi
  kubeRBACProxy:
    image:
      registry: quay.io
      repository: brancz/kube-rbac-proxy
      tag: v0.14.0
    resources:
      limits:
        cpu: 40m
        memory: 40Mi
      requests:
        cpu: 20m
        memory: 20Mi

