{{- if or .Values.additionalPrometheusRules .Values.additionalPrometheusRulesMap}}
apiVersion: v1
kind: List
metadata:
  {{- if .Values.heritageNameOverride }}
  name: prometheus-{{ include "prometheus.heritageName" $ }}-additional-prometheus-rules
  {{- else }}
  name: {{ include "kube-prometheus-stack.fullname" $ }}-additional-prometheus-rules
  {{- end }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
items:
{{- if .Values.additionalPrometheusRulesMap }}
{{- range $prometheusRuleName, $prometheusRule := .Values.additionalPrometheusRulesMap }}
  - apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      {{- if .Values.heritageNameOverride }}
      name: prometheus-{{ include "prometheus.heritageName" $ }}-{{ $prometheusRuleName }}
      {{- else }}
      name: {{ template "kube-prometheus-stack.name" $ }}-{{ $prometheusRuleName }}
      {{- end }}
      namespace: {{ template "kube-prometheus-stack.namespace" $ }}
      labels:
        {{- if .Values.heritageNameOverride }}
        name: prometheus-{{ include "prometheus.heritageName" $ }}
        {{- else }}
        app: {{ template "kube-prometheus-stack.name" $ }}
        {{- end }}
{{ include "kube-prometheus-stack.labels" $ | indent 8 }}
    {{- if $prometheusRule.additionalLabels }}
{{ toYaml $prometheusRule.additionalLabels | indent 8 }}
    {{- end }}
    spec:
      groups:
{{ toYaml $prometheusRule.groups| indent 8 }}
{{- end }}
{{- else }}
{{- range .Values.additionalPrometheusRules }}
  - apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: {{ template "kube-prometheus-stack.name" $ }}-{{ .name }}
      namespace: {{ template "kube-prometheus-stack.namespace" $ }}
      labels:
        {{- if .Values.heritageNameOverride }}
        app: prometheus-{{ include "prometheus.heritageName" $ }}
        {{- else }}
        app: {{ template "kube-prometheus-stack.name" $ }}
        {{- end }}
{{ include "kube-prometheus-stack.labels" $ | indent 8 }}
    {{- if .additionalLabels }}
{{ toYaml .additionalLabels | indent 8 }}
    {{- end }}
    spec:
      groups:
{{ toYaml .groups| indent 8 }}
{{- end }}
{{- end }}
{{- end }}
