{{- if and .Values.prometheus.enabled .Values.prometheus.additionalServiceMonitors }}
apiVersion: v1
kind: List
items:
{{- range .Values.prometheus.additionalServiceMonitors }}
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: {{ .name }}
      namespace: {{ template "kube-prometheus-stack.namespace" $ }}
      labels:
        {{- if $.Values.heritageNameOverride }}
        app: prometheus-{{ include "prometheus.heritageName" $ }}
        {{- else }}
        app: {{ template "kube-prometheus-stack.name" $ }}-prometheus
        {{- end }}
{{ include "kube-prometheus-stack.labels" $ | indent 8 }}
        {{- if .additionalLabels }}
{{ toYaml .additionalLabels | indent 8 }}
        {{- end }}
    spec:
      endpoints:
{{ toYaml .endpoints | indent 8 }}
    {{- if .jobLabel }}
      jobLabel: {{ .jobLabel }}
    {{- end }}
    {{- if .namespaceSelector }}
      namespaceSelector:
{{ toYaml .namespaceSelector | indent 8 }}
    {{- end }}
      selector:
{{- if .selfMonitor }}
        matchLabels:
          {{- if $.Values.heritageNameOverride }}
          app: prometheus-{{ include "prometheus.heritageName" . }}
          {{- else }}
          app: {{ template "kube-prometheus-stack.name" $ }}-prometheus
          {{- end }}
          release: {{ $.Release.Name | quote }}
          self-monitor: "true"
{{- else }}
{{ toYaml .selector | indent 8 }}
{{- end }}
    {{- if .targetLabels }}
      targetLabels:
{{ toYaml .targetLabels | indent 8 }}
    {{- end }}
    {{- if .podTargetLabels }}
      podTargetLabels:
{{ toYaml .podTargetLabels | indent 8 }}
    {{- end }}
{{- end }}
{{- end }}
