{{- if and .Values.prometheus.enabled .Values.prometheus.servicePerReplica.enabled }}
{{- $count := .Values.prometheus.prometheusSpec.replicas | int -}}
{{- $serviceValues := .Values.prometheus.servicePerReplica -}}
apiVersion: v1
kind: List
metadata:
  {{- if .Values.heritageNameOverride }}
  name: prometheus-{{ include "prometheus.heritageName" . }}-serviceperreplica
  {{- else }}
  name: {{ include "kube-prometheus-stack.fullname" $ }}-prometheus-serviceperreplica
  {{- end }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
items:
{{- range $i, $e := until $count }}
  - apiVersion: v1
    kind: Service
    metadata:
      {{- if .Values.heritageNameOverride }}
      name: prometheus-{{ include "prometheus.heritageName" . }}-{{ $i }}
      {{- else }}
      name: {{ include "kube-prometheus-stack.fullname" $ }}-prometheus-{{ $i }}
      {{- end }}
      namespace: {{ template "kube-prometheus-stack.namespace" $ }}
      labels:
        {{- if .Values.heritageNameOverride }}
        app: prometheus-{{ include "prometheus.heritageName" . }}
        {{- else }}
        app: {{ include "kube-prometheus-stack.name" $ }}-prometheus
        {{- end }}
{{ include "kube-prometheus-stack.labels" $ | indent 8 }}
      {{- if $serviceValues.annotations }}
      annotations:
{{ toYaml $serviceValues.annotations | indent 8 }}
      {{- end }}
    spec:
      {{- if $serviceValues.clusterIP }}
      clusterIP: {{ $serviceValues.clusterIP }}
      {{- end }}
      {{- if $serviceValues.loadBalancerSourceRanges }}
      loadBalancerSourceRanges:
      {{- range $cidr := $serviceValues.loadBalancerSourceRanges }}
        - {{ $cidr }}
      {{- end }}
      {{- end }}
      {{- if ne $serviceValues.type "ClusterIP" }}
      externalTrafficPolicy: {{ $serviceValues.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: {{ $.Values.prometheus.prometheusSpec.portName }}
          {{- if eq $serviceValues.type "NodePort" }}
          nodePort: {{ $serviceValues.nodePort }}
          {{- end }}
          port: {{ $serviceValues.port }}
          targetPort: {{ $serviceValues.targetPort }}
      selector:
        app.kubernetes.io/name: prometheus
        {{- if .Values.heritageNameOverride }}
        prometheus: {{ include "prometheus.heritageName" $ }}
        statefulset.kubernetes.io/pod-name: prometheus-{{ include "prometheus.heritageName" $ }}-{{ $i }}
        {{- else }}
        prometheus: {{ include "kube-prometheus-stack.prometheus.crname" $ }}
        statefulset.kubernetes.io/pod-name: prometheus-{{ include "kube-prometheus-stack.prometheus.crname" $ }}-{{ $i }}
        {{- end }}
      type: "{{ $serviceValues.type }}"
{{- end }}
{{- end }}
