{{- if and .Values.kubeControllerManager.enabled .Values.kubeControllerManager.endpoints }}
apiVersion: v1
kind: Endpoints
metadata:
  {{- if .Values.heritageNameOverride }}
  name: kube-controller-manager-svc
  {{- else }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-kube-controller-manager
  {{- end }}
  labels:
    {{- if .Values.heritageNameOverride }}
    app: kube-controller-manager
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" . }}-kube-controller-manager
    {{- end }}
    k8s-app: kube-controller-manager
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
  namespace: kube-system
subsets:
  - addresses:
      {{- range .Values.kubeControllerManager.endpoints }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - name: http-metrics
        {{- $kubeControllerManagerDefaultInsecurePort := 10252 }}
        {{- $kubeControllerManagerDefaultSecurePort := 10257 }}
        port: {{ include "kube-prometheus-stack.kubeControllerManager.insecureScrape" (list . $kubeControllerManagerDefaultInsecurePort $kubeControllerManagerDefaultSecurePort .Values.kubeControllerManager.service.port) }}
        protocol: TCP
{{- end }}
