{{- if .Values.rbac.create }}
{{- if .Values.rbac.pspEnabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
kind: ClusterRole
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  labels: {{ include "prometheus-process-exporter.labels" . | indent 4 }}
  name: psp-{{ template "prometheus-process-exporter.fullname" . }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "prometheus-process-exporter.fullname" . }}
{{- end }}
{{- end }}
{{- end }}