{{- if .Values.coreDns.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  {{- if .Values.heritageNameOverride }}
  name: coredns
  {{- else }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-coredns
  {{- end }}
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    {{- if .Values.heritageNameOverride }}
    app: coredns
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" . }}-coredns
    {{- end }}
  {{- with .Values.coreDns.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
{{- include "kubesphere-monitor.labels" . | indent 4 }}
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      {{- if .Values.heritageNameOverride }}
      k8s-app: kube-dns
      {{- else }}
      app: {{ template "kube-prometheus-stack.name" . }}-coredns
      release: {{ $.Release.Name | quote }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    {{- if .Values.coreDns.serviceMonitor.interval}}
    interval: {{ .Values.coreDns.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.coreDns.serviceMonitor.proxyUrl }}
    proxyUrl: {{ .Values.coreDns.serviceMonitor.proxyUrl}}
    {{- end }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
{{- if .Values.coreDns.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.coreDns.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if .Values.coreDns.serviceMonitor.relabelings }}
    relabelings:
{{ tpl (toYaml .Values.coreDns.serviceMonitor.relabelings | indent 4) . }}
{{- end }}
{{- end }}
