{{- if and .Values.coreDns.enabled .Values.coreDns.service.create }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.heritageNameOverride }}
  name: coredns
  {{- else }}
  name: {{ template "kube-prometheus-stack.fullname" . }}-coredns
  {{- end }}
  labels:
    {{- if .Values.heritageNameOverride }}
    k8s-app: kube-dns
    {{- else }}
    app: {{ template "kube-prometheus-stack.name" . }}-coredns
    {{- end }}
    jobLabel: coredns
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.coreDns.service.port }}
      protocol: TCP
      targetPort: {{ .Values.coreDns.service.targetPort }}
  selector:
    {{- if .Values.coreDns.service.selector }}
{{ toYaml .Values.coreDns.service.selector | indent 4 }}
    {{- else}}
    k8s-app: kube-dns
    {{- end}}
{{- end }}
